// Vercel serverless function: POST /api/generate
// Required environment variable: GROQ_API_KEY
// Generates a ReShade preset .ini + shader.fx using llama-3.1-8b-instant
// Returns text content; the client builds the .zip with JSZip

export default async function handler(request, response) {
  if (request.method !== 'POST') {
    response.setHeader('Allow', 'POST');
    return response.status(405).json({ error: 'Method not allowed.' });
  }

  const { game, style, severity, quality, hardware, palette, prompt, presetName } = request.body || {};

  if (!game || !prompt) {
    return response.status(400).json({ error: 'Game and prompt are required.' });
  }

  const apiKey = process.env.GROQ_API_KEY;
  if (!apiKey) {
    return response.status(500).json({ error: 'Groq API key not configured.' });
  }

  const systemPrompt = `You are a ReShade Preset Engine. Generate a complete preset for the game "${game}".

You MUST respond with ONLY valid JSON in this exact format (no markdown, no code fences, no extra text):
{
  "preset_ini": "[PRESET]...",
  "shader_fx": "// shader code..."
}

Rules:
1. preset_ini must include [PRESET], [Techniques], and [TechniqueSettings] sections with real shader names (Colorfulness.fx, FilmicPass.fx, Levels.fx, LumaSharpen.fx, Vibrance.fx, MagicBloom.fx, Vignette.fx, Curves.fx, Sepia.fx, LiftGammaGain.fx, etc.) and numeric parameters.
2. shader_fx should be a basic HLSL pixel shader with a custom color grade, commented for the preset intent.
3. Style: ${style || 'cinematic'} | Severity: ${severity || 'medium'} | Quality: ${quality || 'balanced'} | Hardware: ${hardware || 'mid'} | Palette: ${palette || 'cinematic'}
4. Return ONLY the JSON object. No explanations, no markdown.`;

  try {
    const groqResponse = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`
      },
      body: JSON.stringify({
        model: 'llama-3.1-8b-instant',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: `Create a preset for ${game}. The user wants: ${prompt}. Style: ${style || 'cinematic'}, Hardware: ${hardware || 'mid'}, Quality: ${quality || 'balanced'}.` }
        ],
        temperature: 0.7,
        max_tokens: 2000
      })
    });

    const data = await groqResponse.json();
    if (!groqResponse.ok) {
      console.error('Groq API error:', data);
      return response.status(502).json({ error: 'Preset generation failed.' });
    }

    const text = data?.choices?.[0]?.message?.content || '';
    
    let presetData;
    try {
      presetData = JSON.parse(text);
    } catch {
      const jsonMatch = text.match(/```(?:json)?\s*([\s\S]*?)```/);
      if (jsonMatch) {
        try {
          presetData = JSON.parse(jsonMatch[1].trim());
        } catch { presetData = null; }
      }
    }

    if (!presetData || !presetData.preset_ini) {
      // Fallback
      presetData = {
        preset_ini: `[PRESET]\nName=${presetName || 'Tactical Preset'}\nGame=${game}\nAuthor=Tactical Web\nDescription=AI-generated preset for ${game}\n\n[Techniques]\nColorfulness.fx=1\nFilmicPass.fx=1\nVignette.fx=1\n\n[TechniqueSettings]\nColorfulness.fx=\n  Colorfulness=1.200000\n  Contrast=1.050000\n  Gamma=1.000000\nFilmicPass.fx=\n  Strength=0.750000\n  Contrast=1.000000\n  Saturation=0.900000\n  Bleach=0.150000\nVignette.fx=\n  Type=1\n  Center=0.500000,0.500000\n  Radius=0.600000\n  Slope=2.000000`,
        shader_fx: `// Tactical Web - ReShade Shader for ${game}\n// Style: ${style || 'cinematic'}\n\nfloat4 PS_Main(float4 color : SV_Target, float2 tex : TEXCOORD0) : SV_Target\n{\n    float3 rgb = color.rgb;\n    float luma = dot(rgb, float3(0.299, 0.587, 0.114));\n    rgb = lerp(rgb, float3(luma, luma, luma), 0.15);\n    return float4(rgb, color.a);\n}`
      };
    }

    const readmeText = `Tactical Web Preset Package\nGame: ${game}\nPrompt: ${prompt}\nStyle: ${style || 'cinematic'}\nHardware: ${hardware || 'mid'}\nQuality: ${quality || 'balanced'}\n\nInstallation:\n1. Copy preset.ini to your ReShade presets folder\n2. Copy shader.fx to your ReShade shaders folder\n3. Load the preset in-game\n\nGenerated by Tactical AI (Groq llama-3.1-8b-instant)`;

    return response.status(200).json({
      preset_ini: presetData.preset_ini,
      shader_fx: presetData.shader_fx,
      readme: readmeText,
      presetName: presetName || 'Tactical Preset'
    });

  } catch (error) {
    console.error('Generate endpoint error:', error);
    return response.status(500).json({ error: 'Something went wrong during generation.' });
  }
}